name: CI AirWatcher

on:
  push:
    branches:
      - main
      - test_erwann

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (build-essential)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with make
        run: make

      - name: Run tests
        run: ./test_exe
